export const GET_LIST_COUNTRIES_REQUEST = "GET_LIST_COUNTRIES_REQUEST";
export const GET_LIST_COUNTRIES_SUCCESS = "GET_LIST_COUNTRIES_SUCCESS";
export const GET_LIST_COUNTRIES_FAIL = "GET_LIST_COUNTRIES_FAIL";

export const GET_LIST_COUNTRY_REQUEST = "GET_LIST_COUNTRY_REQUEST";
export const GET_LIST_COUNTRY_SUCCESS = "GET_LIST_COUNTRY_SUCCESS";
export const GET_LIST_COUNTRY_FAIL = "GET_LIST_COUNTRY_FAIL";

export const GET_DETAILS_COUNTRY_REQUEST = "GET_DETAILS_COUNTRY_REQUEST";
export const GET_DETAILS_COUNTRY_SUCCESS = "GET_DETAILS_COUNTRY_SUCCESS";
export const GET_DETAILS_COUNTRY_FAIL = "GET_DETAILS_COUNTRY_FAIL";
